import AppKit

/// Polls `NSPasteboard.general.changeCount` (the only reliable way to detect
/// clipboard changes on macOS — there is no change event) and feeds new text
/// clips into the store, filtering out our own writes and concealed secrets.
@MainActor
final class PasteboardWatcher {
    private let store: ClipboardStore
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int

    /// nspasteboard.org markers password managers use to flag secrets (§7.3).
    /// Any of these present → never store the clip.
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    init(store: ClipboardStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
        // Seed with the current count so we don't capture whatever was already
        // on the clipboard at launch.
        self.lastChangeCount = pasteboard.changeCount
    }

    func start(interval: TimeInterval = 0.4) {
        guard timer == nil else { return }
        let t = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            // Timer fires on the main run loop, so we're already main-actor isolated.
            MainActor.assumeIsolated { self?.poll() }
        }
        t.tolerance = interval * 0.25 // let the OS coalesce; trims idle wakeups
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return } // O(1) fast path
        lastChangeCount = current

        // Skip the write we caused via select() (§7.2).
        if current == store.lastWrittenChangeCount { return }

        // Privacy: skip concealed / transient / auto-generated clips (§7.3).
        if let types = pasteboard.types, !Self.concealedTypes.isDisjoint(with: types) {
            return
        }

        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }

        // Second guard against our own write, in case another pasteboard write
        // bumped the count between select() and now.
        if text == store.lastWrittenText { return }

        store.add(text)
    }
}
